# Generated by Django 5.2 on 2025-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_alter_productimage_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cred',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_cred',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user_cred',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_cred',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
