# Generated by Django 5.2 on 2025-05-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_user_cred_dob_user_cred_gender_user_cred_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cred',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
