# Generated by Django 5.1.7 on 2025-06-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_user_cred_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
    ]
