# Generated by Django 5.2 on 2025-05-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_remove_products_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='apiApp.products'),
        ),
    ]
